### ISSUE TITLE
Autotick bot not getting 1.2

### ISSUE THREAD

**Issue by asmeurer** [conda-forge/sympy-feedstock#10]
I haven't updated to 1.2 here because I've been waiting for the bot, but it's been almost a week and it hasn't happened yet. @CJ-Wright @justcalamari what is going on?

**Comment by CJ-Wright** [comment]
I'm very sorry for the wait.

GitHub is giving us a 404 error. 
```
2018-07-15 02:09:10,774 INFO     conda_forge_tick.auto_tick || VERSION IS MIGRATING sympy
2018-07-15 02:09:10,895 CRITICAL conda_forge_tick.auto_tick || GITHUB ERROR ON FEEDSTOCK: sympy
404 Not Found
<Response [404]>
```
I'm not certain why. I'll see if we can print out the error.

**Comment by CJ-Wright** [comment]
It seems that this error is during the forking process? (The bot doesn't have a fork of sympy yet)

**Comment by asmeurer** [comment]
Will this be fixed soon or should I just update the feedstock manually?

**Comment by CJ-Wright** [comment]
It should be fixed now, we have a bit of a backlog (about 20 packages) but that should be done about 3 hours. I can speed that up a bit if you need it faster (it may be done sooner than 3 hours depending on where sympy is in the stack).

**Comment by asmeurer** [comment]
If it will come in today that will be fine.

**Comment by justcalamari** [comment]
Thanks for bringing this bug to our attention, @asmeurer.
