### ISSUE TITLE
pypy package?

### ISSUE THREAD

**Issue by asmeurer** [conda-forge/sympy-feedstock#54]
There are currently two sympy 1.12 packages on conda-forge:

```
sympy                           1.12    pyh04b8f61_3  conda-forge
sympy                           1.12 pypyh9d50eac_103  conda-forge
```

Is the second one a pypy package? If so, why is that necessary? SymPy is pure Python. At any rate, it is being preferred for normal Python environments (although it seems to work just fine).

**Comment by isuruf** [comment]
I don't know why the string has `pypy` in it. (probably a conda build bug).
The second package has `gmpy2` as a requirement and the first doesn't. The package with gmpy2 as a requirement has higher priority and is installable only on cpython.
