### ISSUE TITLE
gmpy2 as a hard dependency in the feedstock

### ISSUE THREAD

**Issue by asmeurer** [conda-forge/sympy-feedstock#6]
Is there any opposition to adding gmpy2 as a hard dependency for SymPy on conda-forge (possibly to mpmath as well)? It is technically not a hard dependency of SymPy, but it speeds certain calculations up by quite a bit.  We already do this for fastcache, but that's a much more lightweight dependency. 

@isuruf do you know of any potential issues that might arise?

**Comment by isuruf** [comment]
https://github.com/conda-forge/sympy-feedstock/pull/2#issuecomment-251741768

**Comment by asmeurer** [comment]
Oh yeah :)

**Comment by moorepants** [comment]
This should be closed. Seems gmpy2 is a hard dependency now.
